services:
  app:
    image: dasigr/finance-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=${BASE_URL}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - DRUPAL_API_URL=${DRUPAL_API_URL}
      - DRUPAL_CLIENT_ID=${DRUPAL_CLIENT_ID}
      - DRUPAL_CLIENT_SECRET=${DRUPAL_CLIENT_SECRET}
      - DRUPAL_SCOPE=${DRUPAL_SCOPE}
      - DRUPAL_API_URL_INSECURE=${DRUPAL_API_URL_INSECURE}
      - DRUPAL_ROLE_ID=${DRUPAL_ROLE_ID}
      - SESSION_SECRET=${SESSION_SECRET}
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL_NO_SSL=${POSTGRES_URL_NO_SSL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
